In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/sales_data.csv")
df.head()

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,39,male,Cairo,Headphones,Electronics,1,1760,1760
1,2,nada,63,female,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,1290,1290
3,4,Laila,65,male,Cairo,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         10000 non-null  int64
 1   customer_name    10000 non-null  str
 2   customer_age     10000 non-null  int64
 3   customer_gender  10000 non-null  str
 4   city             10000 non-null  str
 5   product          10000 non-null  str
 6   category         10000 non-null  str
 7   quantity         10000 non-null  int64
 8   unit_price       10000 non-null  int64
 9   total_price      10000 non-null  int64
dtypes: int64(5), str(5)
memory usage: 781.4 KB

In [3]:
df.describe()

          order_id  customer_age      quantity    unit_price    total_price
count  10000.00000  10000.000000  10000.000000  10000.000000   10000.000000
mean    5000.50000     41.415800      2.993100   8973.231500   26598.447000
std     2886.89568     13.836461      1.421075  12317.228491   42269.466174
min        1.00000     18.000000      1.000000    150.000000     150.000000
25%     2500.75000     29.000000      2.000000    777.000000    2234.250000
50%     5000.50000     42.000000      3.000000   2826.500000    7191.500000
75%     7500.25000     53.000000      4.000000   9993.000000   29070.000000
max    10000.00000     65.000000      5.000000  39994.000000  199530.000000

In [3]:
df.columns

Index(['order_id', 'customer_name', 'customer_age', 'customer_gender', 'city',
       'product', 'category', 'quantity', 'unit_price', 'total_price'],
      dtype='str')

In [7]:
df.nunique()

order_id           10000
customer_name          8
customer_age          48
customer_gender        2
city                   8
product                5
category               1
quantity               5
unit_price          6253
total_price         7705
dtype: int64

In [7]:
df.sample(10)

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
5375,5376,Mona,29,female,Suez,Mouse,Electronics,3,698,2094
6365,6366,Ahmed,50,female,Alexandria,Laptop,Electronics,4,28219,112876
6936,6937,nada,43,male,Aswan,Mouse,Electronics,4,506,2024
155,156,Laila,25,female,Cairo,Keyboard,Electronics,3,646,1938
8082,8083,Ahmed,47,male,Aswan,Monitor,Electronics,3,8537,25611
7010,7011,Omar,44,male,Aswan,Laptop,Electronics,1,28035,28035
729,730,Omar,58,male,Alexandria,Laptop,Electronics,5,25287,126435
9873,9874,Ali,44,female,Aswan,Laptop,Electronics,1,29871,29871
2983,2984,Youseef,51,female,Aswan,Laptop,Electronics,5,26246,131230
5788,5789,Mona,33,male,Aswan,Headphones,Electronics,2,2089,4178

In [4]:
df.isna().sum()

order_id           0
customer_name      0
customer_age       0
customer_gender    0
city               0
product            0
category           0
quantity           0
unit_price         0
total_price        0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df["customer_name"].value_counts()

customer_name
Laila      1290
Ali        1268
Ahmed      1264
Youseef    1263
Sara       1261
Omar       1225
Mona       1220
nada       1209
Name: count, dtype: int64

In [7]:
df["city"].value_counts()

city
Cairo         1307
Alexandria    1269
Giza          1267
Aswan         1263
Tanta         1248
Mansoura      1233
Luxor         1210
Suez          1203
Name: count, dtype: int64

In [8]:
df_clean = df.copy()

In [26]:
df_clean.loc[0, "customer_age"] = 150
df_clean.loc[1, "customer_gender"] = None
df_clean.loc[2, "unit_price"] = -500
df_clean.loc[3, "city"] = "paris"
df_clean.head()

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,150,male,Cairo,Headphones,Electronics,1,1760,1760
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,-500,1290
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484
4,5,Laila,39,female,Tanta,Headphones,Electronics,3,1366,4098

In [5]:
df_clean[df_clean["customer_age"] > 100]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [6]:
df_clean[df_clean["unit_price"] < 0]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [20]:
df_clean[df_clean["customer_gender"].isna()]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978

In [22]:
valid_cities = [
    "Cairo",
    "Alexandria",
    "Giza",
    "Mansoura",
    "Tanta",
    "Aswan",
    "Luxor",
    "Suez"]
df_clean[~df_clean["city"].isin(valid_cities)]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
3,4,Laila,65,male,paris,Monitor,Electronics,4,6621,26484

In [27]:
valid_gender = [
    "male",
    "female"]
df_clean[~df_clean["customer_gender"].isin(valid_gender)]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
1,2,nada,63,NaN,Suez,Monitor,Electronics,2,11489,22978

In [28]:
print(
    df_clean[
    df_clean["quantity"] * df_clean["unit_price"] != df_clean["total_price"]
    ]
)
print(
df_clean[
    df_clean["unit_price"] < 0
    ]
)

   order_id customer_name  customer_age customer_gender  city   product  \
2         3           Ali            61          female  Suez  Keyboard

      category  quantity  unit_price  total_price
2  Electronics         1        -500         1290
   order_id customer_name  customer_age customer_gender  city   product  \
2         3           Ali            61          female  Suez  Keyboard

      category  quantity  unit_price  total_price
2  Electronics         1        -500         1290

In [16]:
df_clean[(df_clean["customer_age"] > 60) &
(df_clean["customer_gender"] == "female")]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
1,2,nada,63,female,Suez,Monitor,Electronics,2,11489,22978
2,3,Ali,61,female,Suez,Keyboard,Electronics,1,1290,1290
34,35,Youseef,65,female,Aswan,Mouse,Electronics,2,715,1430
51,52,Mona,65,female,Giza,Laptop,Electronics,5,28716,143580
54,55,Laila,65,female,Cairo,Keyboard,Electronics,4,1411,5644
...,...,...,...,...,...,...,...,...,...,...
9875,9876,Laila,62,female,Aswan,Mouse,Electronics,5,672,3360
9886,9887,Laila,62,female,Luxor,Monitor,Electronics,5,6676,33380
9903,9904,nada,64,female,Suez,Laptop,Electronics,2,29821,59642
9914,9915,Laila,62,female,Alexandria,Laptop,Electronics,1,30719,30719
9994,9995,Ali,65,female,Aswan,Headphones,Electronics,1,3750,3750

In [39]:
df_clean["city"] == "Cairo"

0        True
1       False
2       False
3       False
4       False
        ...
9995     True
9996    False
9997    False
9998    False
9999    False
Name: city, Length: 10000, dtype: bool

In [16]:
df_clean[
    df_clean["city"] == "Cairo"
]

,order_id,customer_name,customer_age,customer_gender,city,product,category,quantity,unit_price,total_price
0,1,Laila,39,male,Cairo,Headphones,Electronics,1,1760,1760
3,4,Laila,65,male,Cairo,Monitor,Electronics,4,6621,26484
39,40,Ahmed,52,female,Cairo,Headphones,Electronics,3,2311,6933
54,55,Laila,65,female,Cairo,Keyboard,Electronics,4,1411,5644
63,64,Mona,38,female,Cairo,Headphones,Electronics,1,4371,4371
...,...,...,...,...,...,...,...,...,...,...
9975,9976,nada,25,male,Cairo,Mouse,Electronics,5,708,3540
9979,9980,Ahmed,27,female,Cairo,Monitor,Electronics,5,11188,55940
9980,9981,Omar,59,female,Cairo,Mouse,Electronics,5,781,3905
9991,9992,Sara,26,female,Cairo,Headphones,Electronics,5,3359,16795
9995,9996,nada,59,female,Cairo,Monitor,Electronics,4,9811,39244

In [15]:
df_clean["customer_age"].median()

np.float64(42.0)

In [17]:
median_age = 42

In [21]:
df_clean.loc[
    df_clean["customer_age"] > 100,
    "customer_age"
    ] = median_age

In [23]:
df_clean[df_clean["customer_age"] > 100]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [44]:
gender_dict = {
    "Ahmed": "male",
    "Sara": "female",
    "Omar": "male",
    "Mona": "female",
    "Ali": "male",
    "Youseef": "male",
    "nada": "female",
    "Laila": "female"
}
gender_from_name = df_clean["customer_name"].map(gender_dict)

In [45]:
df_clean["customer_gender"] = df_clean["customer_gender"].fillna(gender_from_name)

In [46]:
df_clean["customer_gender"].isna().sum()

np.int64(0)

In [48]:
df_clean[df_clean["customer_gender"].isna()]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [49]:
gender_dict

{'Ahmed': 'male',
 'Sara': 'female',
 'Omar': 'male',
 'Mona': 'female',
 'Ali': 'male',
 'Youseef': 'male',
 'nada': 'female',
 'Laila': 'female'}

In [7]:
df_clean[df_clean["unit_price"] < 0]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []

In [8]:
df_clean["unit_price"].min()

np.int64(150)

In [12]:
age_median = df_clean[(df_clean["customer_age"] >= 0 ) & (df_clean["customer_age"]<= 100)]["customer_age"].median()

In [14]:
df_clean.loc[
    ~(
        (df_clean["customer_age"] >= 0) &
        (df_clean["customer_age"] <= 100)
    ),
    "customer_age"
] = age_median

In [15]:
df_clean[
    ~(
        (df_clean["customer_age"] >= 0) &
        (df_clean["customer_age"] <= 100)
    )
]

Empty DataFrame
Columns: [order_id, customer_name, customer_age, customer_gender, city, product, category, quantity, unit_price, total_price]
Index: []